# Generated by Django 3.0.3 on 2020-03-12 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_publicacao_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="categoria_pai",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categorias",
                related_query_name="categoria",
                to="core.Categoria",
            ),
        ),
    ]
